<?xml version="1.0" encoding="UTF-8"?>
<project name="com.sina.weibo.agent.eclipse" default="build.jars" basedir=".">

	<property name="plugin.name" value="com.sina.weibo.agent.eclipse"/>
	<property name="build.result.folder" value="build"/>
	<property name="plugin.destination" value="${build.result.folder}/${plugin.name}.jar"/>

	<target name="init">
		<mkdir dir="${build.result.folder}"/>
	</target>

	<target name="build.jars" depends="init">
		<antcall target="build.jar"/>
	</target>

	<target name="build.jar">
		<jar destfile="${plugin.destination}" manifest="META-INF/MANIFEST.MF">
			<fileset dir="bin" includes="**/*.class"/>
			<fileset dir="." includes="plugin.xml, META-INF/"/>
		</jar>
	</target>

</project>
